# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title: Landi
description: Landscape Gardening Jekyll Theme.

# Site base hostname & protocol, e.g. http://example.com
url: ''

# Site subpath, e.g. /blog
baseurl: "/landi-Jekyll-theme-live"

# Number of posts displayed on blog page
paginate: 7

# Blog path
paginate_path: "/blog/:num/"
permalink: /:title/

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname: twinkletheme

# Google Analytics
google_analytics: #UA—XXXXXXXX-X

# Build settings
plugins:
  - jekyll-liquify
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll/tagging

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Authors
authors:
  andrew:
    name:       Andrew Phili
    bio:        Et harum quidem rerum facilis est et expedita distinctio. Nam tempore, soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est,
    gravatar:   assets/images/blog/author-avatar.jpg
    facebook:   https://facebook.com/twinkletheme
    twitter:    https://twitter.com/twinkletheme
    pinterest:  https://pinterest.com/twinkletheme
